const dataArray=[
    {
        name: "/dashboard",
        componentName: "Organization",
        mainMenu: "Dashboard",
        subMenu:"",
        pageName: "Dashboard",
        parentRouteId:6,
      },
      {
        name: "/employees",
        componentName: "Organization",
        mainMenu: "Employees",
        subMenu:"",
        pageName: "Employees",
        parentRouteId:6,
      },
      {
        name: "/orgstructure",
        componentName: "Organization",
        mainMenu: "Org Structure",
        subMenu:"",
        pageName: "Org Structure",
        parentRouteId:6,
      },
      {
        name: "/onboarding",
        componentName: "Organization",
        mainMenu: "Onboarding",
        subMenu:"",
        pageName: "Onboarding",
        parentRouteId:6,
      },
      {
        name: "/exits",
        componentName: "Organization",
        mainMenu: "exits",
        subMenu:"",
        pageName: "exits",
        parentRouteId:6,
      },
      {
        name: "/expenses&travel",
        componentName: "Organization",
        mainMenu: "Expenses & Travel",
        subMenu:"",
        pageName: "Expenses & Travel",
        parentRouteId:6,
      },
      {
        name: "/documents",
        componentName: "Organization",
        mainMenu: "Documents",
        subMenu:"",
        pageName: "Documents",
        parentRouteId:6,
      },
      {
        name: "/engage",
        componentName: "Organization",
        mainMenu: "Engage",
        subMenu:"",
        pageName: "Engage",
        parentRouteId:6,
      },
      {
        name: "/assets",
        componentName: "Organization",
        mainMenu: "Assets",
        subMenu:"",
        pageName: "Assets",
        parentRouteId:6,
      },
      {
        name: "/helpdesk",
        componentName: "Organization",
        mainMenu: "Helpdesk",
        subMenu:"",
        pageName: "Helpdesk",
        parentRouteId:6,
      },
      {
        name: "/hiring",
        componentName: "Organization",
        mainMenu: "Hiring",
        subMenu:"",
        pageName: "Hiring",
        parentRouteId:6,
      },
      {
        name: "/settings",
        componentName: "Organization",
        mainMenu: "Settings",
        subMenu:"",
        pageName: "Settings",
        parentRouteId:6,
      },
        {
          name: "/summary",
          componentName: "Organization",
          mainMenu: "Dashboard",
          subMenu:"Summary",
          pageName: "Summary",
          parentRouteId:43,
        },
        {
          name: "/analytics",
          componentName: "Organization",
          mainMenu: "Dashboard",
          subMenu:"Analytics",
          pageName: "Analytics",
          parentRouteId:43,
        },
        {
          name: "/employeereports",
          componentName: "Organization",
          mainMenu: "Dashboard",
          subMenu:"Employee Reports",
          pageName: "Employee Reports",
          parentRouteId:43,
        },
        {
          name: "/employeedirectory",
          componentName: "Organization",
          mainMenu: "Employees",
          subMenu:"Employee Directory",
          pageName: "Employee Directory",
          parentRouteId:44,
        },
        {
          name: "/organizationtree",
          componentName: "Organization",
          mainMenu: "Employees",
          subMenu:"Organization Tree",
          pageName: "Organization Tree",
          parentRouteId:44,
        },
        {
          name: "/login",
          componentName: "Organization",
          mainMenu: "Employees",
          subMenu:"Login",
          pageName: "Login",
          parentRouteId:44,
        },
        {
          name: "/contingentstaff",
          componentName: "Organization",
          mainMenu: "Employees",
          subMenu:"Contingent Staff",
          pageName: "Contingent Staff",
          parentRouteId:44,
        },
        {
          name: "/profilechanges",
          componentName: "Organization",
          mainMenu: "Employees",
          subMenu:"Profile Changes",
          pageName: "Profile Changes",
          parentRouteId:44,
        },
        {
          name: "/privateprofiles",
          componentName: "Organization",
          mainMenu: "Employees",
          subMenu:"Private Profiles",
          pageName: "Private Profiles",
          parentRouteId:44,
        },
        {
          name: "/probation",
          componentName: "Organization",
          mainMenu: "Employees",
          subMenu:"Probation",
          pageName: "Probation",
          parentRouteId:44,
        },
        {
          name: "/settings",
          componentName: "Organization",
          mainMenu: "Employees",
          subMenu:"Settings",
          pageName: "Settings",
          parentRouteId:44,
        },    
            {
              name: "/loginregistrations",
              componentName: "Organization",
              mainMenu: "Login",
              subMenu:"Login Registrations",
              pageName: "Login Registrations",
              parentRouteId:60,
            },
            {
              name: "/loginhistory",
              componentName: "Organization",
              mainMenu: "Login",
              subMenu:"Login History",
              pageName: "Login History",
              parentRouteId:60,
            },
            {
              name: "/loginfailed",
              componentName: "Organization",
              mainMenu: "Login",
              subMenu:"Login Failed",
              pageName: "Login Failed",
              parentRouteId:60,
            },
            {
              name: "/summary",
              componentName: "Organization",
              mainMenu: "Contingent Staff",
              subMenu:"Summary",
              pageName: "Summary",
              parentRouteId:61,
            },
            {
              name: "/worktypes",
              componentName: "Organization",
              mainMenu: "Contingent Staff",
              subMenu:"Work Types",
              pageName: "Work Types",
              parentRouteId:61,
            },
            {
              name: "/profileapprovals",
              componentName: "Organization",
              mainMenu: "Profile Changes",
              subMenu:"profileapprovals",
              pageName: "profileapprovals",
              parentRouteId:62,
            },
            {
              name: "/pastchanges",
              componentName: "Organization",
              mainMenu: "Profile Changes",
              subMenu:"Past Changes",
              pageName: "Past Changes",
              parentRouteId:62,
            },
            {
              name: "/inprobation",
              componentName: "Organization",
              mainMenu: "Probation",
              subMenu:"In Probation",
              pageName: "In Probation",
              parentRouteId:64,
            },
            {
              name: "/evaluationinprogress",
              componentName: "Organization",
              mainMenu: "Probation",
              subMenu:"Evaluation In Progress",
              pageName: "Evaluation In Progress",
              parentRouteId:64,
            },
            {
              name: "/completedprobationactions",
              componentName: "Organization",
              mainMenu: "Probation",
              subMenu:"Completed Probation Actions",
              pageName: "Completed Probation Actions",
              parentRouteId:64,
            },
            {
              name: "/probationpolicy",
              componentName: "Organization",
              mainMenu: "Probation",
              subMenu:"Probation Policy",
              pageName: "Probation Policy",
              parentRouteId:64,
            },
            {
              name: "/probationfeedbackform",
              componentName: "Organization",
              mainMenu: "Probation",
              subMenu:"Probation Feedback Form",
              pageName: "Probation Feedback Form",
              parentRouteId:64,
            },
          
            {
              name: "/employeedefaults",
              componentName: "Organization",
              mainMenu: "Settings",
              subMenu:"Employee Defaults",
              pageName: "Employee Defaults",
              parentRouteId:65,
            },
            {
              name: "/jobtitles",
              componentName: "Organization",
              mainMenu: "Settings",
              subMenu:"Job Titles",
              pageName: "Job Titles",
              parentRouteId:65,
            },
            {
              name: "/employeenumber",
              componentName: "Organization",
              mainMenu: "Settings",
              subMenu:"Employee Number",
              pageName: "Employee Number",
              parentRouteId:65,
            },
            {
              name: "/timeline",
              componentName: "Organization",
              mainMenu: "Settings",
              subMenu:"Timeline",
              pageName: "Timeline",
              parentRouteId:65,
            },
            {
              name: "/wall",
              componentName: "Organization",
              mainMenu: "Settings",
              subMenu:"Wall",
              pageName: "Wall",
              parentRouteId:65,
            },
            {
              name: "/personalinfo",
              componentName: "Organization",
              mainMenu: "Settings",
              subMenu:"Personal Info",
              pageName: "Personal Info",
              parentRouteId:65,
            },
            {
              name: "/idcard",
              componentName: "Organization",
              mainMenu: "Settings",
              subMenu:"ID Card",
              pageName: "ID Card",
              parentRouteId:65,
            },
            {
              name: "/dottedlinemanager",
              componentName: "Organization",
              mainMenu: "Settings",
              subMenu:"Dotted Line Manager",
              pageName: "Dotted Line Manager",
              parentRouteId:65,
            },
        
              {
                  name: "/summary",
                  componentName: "Organization",
                  mainMenu: "Onboarding",
                  subMenu:"Summary",
                  pageName: "Summary",
                  parentRouteId:46,
                },
                {
                  name: "/initiateonboarding",
                  componentName: "Organization",
                  mainMenu: "Onboarding",
                  subMenu:"Initiate Onboarding",
                  pageName: "Initiate Onboarding",
                  parentRouteId:46,
                }, {
                  name: "/onboardinggroups",
                  componentName: "Organization",
                  mainMenu: "Onboarding",
                  subMenu:"Onboarding Groups",
                  pageName: "Onboarding Groups",
                  parentRouteId:46},
                  {
                      name: "/tasks",
                      componentName: "Organization",
                      mainMenu: "Onboarding",
                      subMenu:"Tasks",
                      pageName: "Tasks",
                      parentRouteId:46,
                    },
                    {
                      name: "/settings",
                      componentName: "Organization",
                      mainMenu: "Onboarding",
                      subMenu:"Settings",
                      pageName: "Settings",
                      parentRouteId:46,
                    },
                    {
                      name: "/exitdashboard",
                      componentName: "Organization",
                      mainMenu: "Exits",
                      subMenu:"Exit dashboard",
                      pageName: "Exit Dashboard",
                      parentRouteId:47,
                    },
                    {
                      name: "/pendingapprovals",
                      componentName: "Organization",
                      mainMenu: "Exits",
                      subMenu:"Pending Approvals",
                      pageName: "Pending Approvals",
                      parentRouteId:47,
                    },
                    {
                      name: "/full&final",
                      componentName: "Organization",
                      mainMenu: "Exits",
                      subMenu:"Full & Final",
                      pageName: "Full & Final",
                      parentRouteId:47,
                    },
                    {
                      name: "/revertedexits",
                      componentName: "Organization",
                      mainMenu: "Exits",
                      subMenu:"Reverted Exits",
                      pageName: "Reverted Exits",
                      parentRouteId:47,
                    },
                    {
                      name: "/exitedemployees",
                      componentName: "Organization",
                      mainMenu: "Exits",
                      subMenu:"Exited Employees",
                      pageName: "Exited Employees",
                      parentRouteId:47,
                    },
                    {
                      name: "/tasks",
                      componentName: "Organization",
                      mainMenu: "Exits",
                      subMenu:"Tasks",
                      pageName: "Tasks",
                      parentRouteId:47,
                    },
                    {
                      name: "/exitsurvey",
                      componentName: "Organization",
                      mainMenu: "Exits",
                      subMenu:"Exit Survey",
                      pageName: "Exit Survey",
                      parentRouteId:47,
                    },
                    {
                      name: "/settings",
                      componentName: "Organization",
                      mainMenu: "Exits",
                      subMenu:"settings",
                      pageName: "settings",
                      parentRouteId:47,
                    },
                    {
                      name: "/bulkactions",
                      componentName: "Organization",
                      mainMenu: "Exits",
                      subMenu:"Bulk Actions",
                      pageName: "Bulk Actions",
                      parentRouteId:47,
                    },
                    {
                      name: "/mydeclaration",
                      componentName: "My Finances",
                      mainMenu: "Declaration",
                      subMenu:"My Declaration",
                      pageName: "My Declaration",
                      parentRouteId:38,
                    }, {
                      name: "/lacdeduction",
                      componentName: "My Finances",
                      mainMenu: "Declaration",
                      subMenu:"1.5 Lac Deduction",
                      pageName: "1.5 Lac Deduction",
                      parentRouteId:38,
                    }, {
                      name: "/otherdeductions",
                      componentName: "My Finances",
                      mainMenu: "Declaration",
                      subMenu:"Other Deductions",
                      pageName: "Other Deductions",
                      parentRouteId:38,
                    },
                    {
                      name: "/taxsavingallowances",
                      componentName: "My Finances",
                      mainMenu: "Declaration",
                      subMenu:"Tax Saving Allowances",
                      pageName: "Tax Saving Allowances",
                      parentRouteId:38,
                    },
                    {
                      name: "/houseproperty",
                      componentName: "My Finances",
                      mainMenu: "Declaration",
                      subMenu:"House Property",
                      pageName: "House Property",
                      parentRouteId:38,
                    },
                    {
                      name: "/incomefromothersources",
                      componentName: "My Finances",
                      mainMenu: "Declaration",
                      subMenu:"Income From Other Sources",
                      pageName: "Income From Other Sources",
                      parentRouteId:38,
                    }
                  
,                  
                    {
                      name: "/dashboard",
                      componentName: "Project Management",
                      mainMenu: "Dashboard",
                      subMenu:"",
                      pageName: "Dashboard",
                      parentRouteId:8,
                    },
                    {
                      name: "/allteams",
                      componentName: "Project Management",
                      mainMenu: "All Teams",
                      subMenu:"",
                      pageName: "All Teams",
                      parentRouteId:8,
                    },
                    {
                      name: "/allprojects",
                      componentName: "Project Management",
                      mainMenu: "All Projects",
                      subMenu:"",
                      pageName: "All Projects",
                      parentRouteId:8,
                    },
                    {
                      name: "/tasks",
                      componentName: "Project Management",
                      mainMenu: "Tasks",
                      subMenu:"",
                      pageName: "Tasks",
                      parentRouteId:8,
                    },
                    
                    {
                      name: "/timeline",
                      componentName: "Project Management",
                      mainMenu: "Tasks",
                      subMenu:"Timeline",
                      pageName: "Timeline",
                      parentRouteId:113,
                    },
                    {
                      name: "/sprints",
                      componentName: "Project Management",
                      mainMenu: "Tasks",
                      subMenu:"Sprints",
                      pageName: "Sprints",
                      parentRouteId:113,
                    },{   name: "/boards",
                      componentName: "Project Management",
                      mainMenu: "Tasks",
                      subMenu:"Boards",
                      pageName: "Boards",
                      parentRouteId:113,
                    },{   name: "/issues",
                      componentName: "Project Management",
                      mainMenu: "Tasks",
                      subMenu:"Issues",
                      pageName: "Issues",
                      parentRouteId:113,
                    },

                    const dataArray=[
                      {   
                        name: "/dashboard",
                        componentName: "Time and Attendance",
                        mainMenu: "Dashboard",
                        subMenu:"",
                        pageName: "Dashboard",
                        parentRouteId:9,
                      },
                      {   
                        name: "/approvals",
                        componentName: "Time and Attendance",
                        mainMenu: "Approvals",
                        subMenu:"",
                        pageName: "Approvals",
                        parentRouteId:9,
                      },
                      {   
                        name: "/weeklyoffs&holidays",
                        componentName: "Time and Attendance",
                        mainMenu: "Shifts/weekly offs & holidays",
                        subMenu:"",
                        pageName: "Shifts/Weekly Offs & Holidays",
                        parentRouteId:9,
                      },
                      {   
                        name: "/attendancetracking",
                        componentName: "Time and Attendance",
                        mainMenu: "Attendance Tracking",
                        subMenu:"",
                        pageName: "Attendance Tracking",
                        parentRouteId:9,
                      },
                      {   
                        name: "/overtime",
                        componentName: "Time and Attendance",
                        mainMenu: "Overtime",
                        subMenu:"",
                        pageName: "Overtime",
                        parentRouteId:9,
                      },
                      {   
                        name: "/leave",
                        componentName: "Time and Attendance",
                        mainMenu: "Leave",
                        subMenu:"",
                        pageName: "Leave",
                        parentRouteId:9,
                      },
                      {   
                        name: "/reports",
                        componentName: "Time and Attendance",
                        mainMenu: "Reports",
                        subMenu:"",
                        pageName: "Reports",
                        parentRouteId:9,
                      },
                      {   
                        name: "/settings",
                        componentName: "Time and Attendance",
                        mainMenu: "Settings",
                        subMenu:"",
                        pageName: "Settings",
                        parentRouteId:9,
                      }
                    ]





                    {   
                      name: "/attendancesummary",
                      componentName: "Time and Attendance",
                      mainMenu: "Attendance Summary",
                      subMenu:"",
                      pageName: "Attendance Summary",
                      parentRouteId:118,
                    },

                    const dataArray=[
                      {   
                        name: "/attendancesummary",
                        componentName: "Time and Attendance",
                        mainMenu: "Dashboard",
                        subMenu:"Attendance Summary",
                        pageName: "Attendance Summary",
                        parentRouteId:118,
                      },
                      {   
                        name: "/attendanceanalytics",
                        componentName: "Time and Attendance",
                        mainMenu: "Dashboard",
                        subMenu:"Attendance Analytics",
                        pageName: "Attendance Analytics",
                        parentRouteId:118,
                      },
                      {   
                        name: "/leavesummary",
                        componentName: "Time and Attendance",
                        mainMenu: "Dashboard",
                        subMenu:"Leave Summary",
                        pageName: "Leave Summary",
                        parentRouteId:118,
                      },
                      {   
                        name: "/leaveanalytics",
                        componentName: "Time and Attendance",
                        mainMenu: "Dashboard",
                        subMenu:"Leave Analytics",
                        pageName: "Leave Analytics",
                        parentRouteId:118,
                      },
                    
                      {   
                        name: "/leave",
                        componentName: "Time and Attendance",
                        mainMenu: "Approvals",
                        subMenu:"Leave",
                        pageName: "Leave",
                        parentRouteId:119,
                      },
                      {   
                        name: "/leaveencashment",
                        componentName: "Time and Attendance",
                        mainMenu: "Approvals",
                        subMenu:"Leave Encashment",
                        pageName: "Leave Encashment",
                        parentRouteId:119,
                      },
                      {   
                        name: "/campoffs",
                        componentName: "Time and Attendance",
                        mainMenu: "Approvals",
                        subMenu:"Camp Offs",
                        pageName: "Camp Offs",
                        parentRouteId:119,
                      },
                      {   
                        name: "/regularizations",
                        componentName: "Time and Attendance",
                        mainMenu: "Approvals",
                        subMenu:"Regularizations",
                        pageName: "Regularizations",
                        parentRouteId:119,
                      },
                      {   
                        name: "/wfh/od",
                        componentName: "Time and Attendance",
                        mainMenu: "Approvals",
                        subMenu:"WFH/OD",
                        pageName: "WFH/OD",
                        parentRouteId:119,
                      },
                      {   
                        name: "/webclockin",
                        componentName: "Time and Attendance",
                        mainMenu: "Approvals",
                        subMenu:"Web Clock-in",
                        pageName: "Web Clock-in",
                        parentRouteId:119,
                      },
                      {   
                        name: "/partialday",
                        componentName: "Time and Attendance",
                        mainMenu: "Approvals",
                        subMenu:"Partial Day",
                        pageName: "Partial Day",
                        parentRouteId:119,
                      },
                      {   
                        name: "/overtime",
                        componentName: "Time and Attendance",
                        mainMenu: "Approvals",
                        subMenu:"Overtime",
                        pageName: "Overtime",
                        parentRouteId:119,
                      },
                      {   
                        name: "/shift&weeklyoff",
                        componentName: "Time and Attendance",
                        mainMenu: "Approvals",
                        subMenu:"Shift & Weekly off",
                        pageName: "Shift & Weekly off",
                        parentRouteId:119,
                      },
                    
                    
                      {   
                        name: "/shift&weeklyoffs",
                        componentName: "Time and Attendance",
                        mainMenu: "Shifts/weekly offs & holidays",
                        subMenu:"Shift & Weekly offs",
                        pageName: "Shift & Weekly offs",
                        parentRouteId:120,
                      },
                      {   
                        name: "/shiftallowance",
                        componentName: "Time and Attendance",
                        mainMenu: "Shifts/weekly offs & holidays",
                        subMenu:"Shift Allowances",
                        pageName: "Shift Allowances",
                        parentRouteId:120,
                      },
                    
                      {   
                        name: "/assignments",
                        componentName: "Time and Attendance",
                        mainMenu: "Shifts/weekly offs & holidays",
                        subMenu:"Assignments",
                        pageName: "Assignments",
                        parentRouteId:120,
                      },
                    
                      {   
                        name: "/scheduler",
                        componentName: "Time and Attendance",
                        mainMenu: "Shifts/weekly offs & holidays",
                        subMenu:"Scheduler",
                        pageName: "Scheduler",
                        parentRouteId:120,
                      },
                      {   
                        name: "/holidays",
                        componentName: "Time and Attendance",
                        mainMenu: "Shifts/weekly offs & holidays",
                        subMenu:"Holidays",
                        pageName: "Holidays",
                        parentRouteId:120,
                      }
                    
                    
                    ]

                    const dataArray=[
                      {
                      name: "/shifts",
                      componentName: "Time and Attendance",
                      mainMenu: "Shift & Weekly Offs",
                      subMenu:"Shifts",
                      pageName: "Shifts",
                      parentRouteId:139
                      },
                      {
                        name: "/weeklyoffs",
                        componentName: "Time and Attendance",
                        mainMenu: "Shift & Weekly Offs",
                        subMenu:"Weekly Offs",
                        pageName: "Weekly Offs",
                        parentRouteId:139
                        },
                        {
                          name: "/shift&weeklyoffrules",
                          componentName: "Time and Attendance",
                          mainMenu: "Shift & Weekly Offs",
                          subMenu:"Shift & Weekly off Rules",
                          pageName: "Shift & Weekly Off Rules",
                          parentRouteId:139
                          },
                    
                    
                          {
                            name: "/shiftallowancepolicy",
                            componentName: "Time and Attendance",
                            mainMenu: "Shift Allowances",
                            subMenu:"Shift Allowance Policy",
                            pageName: "Shift Allowance Policy",
                            parentRouteId:140
                            },
                    
                            {
                              name: "/shiftallowancecode",
                              componentName: "Time and Attendance",
                              mainMenu: "Shift Allowances",
                              subMenu:"Shift Allowance Code",
                              pageName: "Shift Allowance Code",
                              parentRouteId:140
                              },
                    
                    
                              {
                                name: "/shift&weeklyoffassignments",
                                componentName: "Time and Attendance",
                                mainMenu: "Assignments",
                                subMenu:"Shift & Weekly Off Assignments",
                                pageName: "Shift & Weekly Off Assignments",
                                parentRouteId:141
                                },
                    
                                {
                                  name: "/shiftallowanceassignments",
                                  componentName: "Time and Attendance",
                                  mainMenu: "Assignments",
                                  subMenu:"Shift Allowance Assignments",
                                  pageName: "Shift Allowance Assignments",
                                  parentRouteId:141
                                  },
                                  {
                                    name: "/shift&weeklyoffrulesassignments",
                                    componentName: "Time and Attendance",
                                    mainMenu: "Assignments",
                                    subMenu:"Shift & Weekly Off Rules Assignments",
                                    pageName: "Shift & Weekly Off Rules Assignments",
                                    parentRouteId:141
                                    },
                    
                    
                                    {
                                      name: "/shiftboard",
                                      componentName: "Time and Attendance",
                                      mainMenu: "Scheduler",
                                      subMenu:"Shift Board",
                                      pageName: "Shift Board",
                                      parentRouteId:142
                                      },
                    
                                      {
                                        name: "/shiftrotation",
                                        componentName: "Time and Attendance",
                                        mainMenu: "Scheduler",
                                        subMenu:"Shift Rotation",
                                        pageName: "Shift Rotation",
                                        parentRouteId:142
                                        },
                    ]
]
const dataArray=[
  {
      name: "/payrollanalytics",
      componentName: "Payroll",
      mainMenu: "Payroll Analytics",
      subMenu:"",
      pageName: "Payroll Analytics",
      parentRouteId:10
      },
      {
          name: "/runpayroll",
          componentName: "Payroll",
          mainMenu: "Run Payroll",
          subMenu:"",
          pageName: "Run Payroll",
          parentRouteId:10
          },
          {
              name: "/payrolladmin",
              componentName: "Payroll",
              mainMenu: "Payroll Admin",
              subMenu:"",
              pageName: "Payroll Admin",
              parentRouteId:10
              },

              {
                  name: "/loans",
                  componentName: "Payroll",
                  mainMenu: "Loans",
                  subMenu:"",
                  pageName: "Loans",
                  parentRouteId:10
                  },
                  {
                      name: "/perks",
                      componentName: "Payroll",
                      mainMenu: "Perks",
                      subMenu:"",
                      pageName: "Perks",
                      parentRouteId:10
                      },
                      {
                          name: "/reports",
                          componentName: "Payroll",
                          mainMenu: "Reports",
                          subMenu:"",
                          pageName: "Reports",
                          parentRouteId:10
                          },
                          {
                              name: "/settings",
                              componentName: "Payroll",
                              mainMenu: "Settings",
                              subMenu:"",
                              pageName: "Settings",
                              parentRouteId:10
                              },

                              
const dataArray=[
  {
      name: "/analytics",
      componentName: "Payroll",
      mainMenu: "Payroll Analytics",
      subMenu:"Analytics",
      pageName: "Analytics",
      parentRouteId:154
  },
  {
      name: "/compensationplanning",
      componentName: "Payroll",
      mainMenu: "Payroll Analytics",
      subMenu:"Compensation Planning",
      pageName: "Compensation Planning",
      parentRouteId:154
  },
  {
      name: "/budgetestimation",
      componentName: "Payroll",
      mainMenu: "Payroll Analytics",
      subMenu:"Budget Estimation",
      pageName: "Budget Estimation",
      parentRouteId:154
  },
  {
      name: "/comparecompensationstat",
      componentName: "Payroll",
      mainMenu: "Payroll Analytics",
      subMenu:"Compare Compensation Stat",
      pageName: "Compare Compensation Stat",
      parentRouteId:154
  },
  {
      name: "/employeecompetitiveness",
      componentName: "Payroll",
      mainMenu: "Payroll Analytics",
      subMenu:"Employee Competitiveness",
      pageName: "Employee Competitiveness",
      parentRouteId:154
  },
  {
      name: "/budgetestimation",
      componentName: "Payroll",
      mainMenu: "Payroll Analytics",
      subMenu:"Budget Estimation",
      pageName: "Budget Estimation",
      parentRouteId:154
  }




]
]